# BIN = foo

# OBJ = foo.o

# SRC = singly-linked-list.c

SRC = doubly-linked-list.c

# SRC = circularly-linked-list.c

FLAGS = -ggdb3 -std=c11 -w

CC = gcc

all:
	$(CC) $(FLAGS) $(SRC)
clean:
	rm -f a.out *~
	clear
