BIN = singlylinkedlist

OBJ = singlylinkedlist.o

SRC = singlylinkedlist.c

FLAGS = -g -glldb -w -std=c11

CC = clang

all: singlylinkedlist.c
	$(CC) $(FLAGS) $(SRC) -o $(BIN)
clean:
	rm -f $(BIN) $(OBJ) *~
	clear
