#!/bin/bash

sed -i \
-e "s/RIM MI HAN/RI MYONG GUK/g" \
-e "s/PAK JUN CHOL/PAK CHOL JIN/g" \
-e "s/RIM JIN WOO/RI JUN IL/g" \
-e "s/RI KANG CHOL/RI KWANG CHON/g" \
-e "s/CHO JIN HYON/CHA JONG HYOK/g" \
-e "s/JI GWAN SONG/JI YUN NAM/g" \
-e "s/AN HAN YOL/AN YONG HAK/g" \
-e "s/MUN HAN SOK/MUN IN GUK/g" \
-e "s/PAK EUN DOK/PAK NAM CHOL/g" \
-e "s/HONG TAE YUN/HONG YONG JO/g" \
-e "s/CHONG JUNG WON/JONG TAE SE/g" \
-e "s/KIM MIN GON/KIM MYONG GIL/g" \
-e "s/AN CHONHYON/AN CHOL HYOK/g" \
-e "s/PAK HANCHON/PAK NAM CHOL/g" \
-e "s/RIM KAN HO/RI KWANG HYOK/g" \
-e "s/PAK SANG HUN/PAK SUNG HYOK/g" \
-e "s/RI CHANG MIN/RI CHOL MYONG/g" \
-e "s/KIM KANG IN/KIM KYONG IL/g" \
-e "s/NAM SUNG CHAN/NAM SONG CHOL/g" \
-e "s/KIM SUNG JIN/KIM YONG JUN/g" \
-e "s/KIM MUN GIL/KIM KUM IL/g" \
-e "s/CHOE GUN CHAN/CHOE KUM CHOL/g" \
-e "s/KIM MIN HAN/KIM MYONG WON/g" ~/nkorea.csv
