BIN = circularlinkedlist

OBJ = circularlinkedlist.o

SRC = circularlinkedlist.c

FLAGS = -g -glldb -w -std=c11

CC = clang

all: circularlinkedlist.c
	$(CC) $(FLAGS) $(SRC) -o $(BIN)
clean:
	rm -f $(BIN) $(OBJ) *~
	clear
